### PR TITLE
Adding new modules

### PR DESCRIPTION
**Pull request by narukeh**
Adding new modules, terminal, resolution, and maybe `ip` if i can...
pic-selected-231022-1338-13

p.s.: really nice that you are maintaining posix pfetch 💪

### CODE REVIEW

**Comment by narukeh** [comment]
i am also working on a `ip` module but im having trouble displaying it.
here is the main magic:
```bash
ip a | grep 'inet ' | awk '{print $2}' | grep -v '127.0.0.1'
```

**Comment by xplshn** [comment]
Hi, could you add something like this to the PR too? I implemented it but its too janky.

2024-01-06-123609_306x167_scrot

**Comment by narukeh** [comment]
thats really dope
post your diff so that i dont have to start from scratch 😅
but i dont think he is merging PRs anyways.....

**Comment by xplshn** [comment]
Heh, okay. You have to disable the normal palette and set PF_VERTP=1 to display it:

https://github.com/narukeh/pfetch/compare/master...xplshn:pfetch:master

There it is. Tell me what you think, I am quite useless when it comes to scripting.

**Comment by OldWorldOrdr** [comment]
Not sure how I didn't see this for so long, my notifications must be broken or something

**Comment by xplshn** [comment]
Hi! @OldWorldOrdr., Did you add the vertical color palette? Or is it too out of scope?

**Comment by OldWorldOrdr** [comment]
You can make another or if you want

**Comment by xplshn** [comment]
I don't know how to make it work when specified in PF_INFO, like, if palette and pfvertp are in that variable

**Comment by OldWorldOrdr** [comment]
Sorry autocorrect, you can make another PR for the vertical colors, I might look at the diff and merge it myself anyway.

**Comment by xplshn** [comment]
Ah, okay.

**Pull request merged**
